#server:
#  port: 8781
spring:
  application:
    name: service-client
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
name: test 变化
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
